fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "brunel.jeremy9@gmail.com"
    sender_name: "brunel.jeremy9@gmail.com"